RegistrationEvent:
  - callback: RegisterVisitorToNewsLetterListener
    priority: 0
  - callback: EmailSenderlistener
    priority: 1
ForgotPasswordEvent:
  - callback: EmailSenderlistener
    priority: 0
EmailVerificationEvent:
  - callback: EmailSenderlistener
    priority: 0
