request: RequestHandler
response: ResponseHandler
formBuilder: FormBuilder
eventDispatcher: EventDispatcher
error: App\Core\Error\Error
tableGrid: Datatable
collection: App\Core\Collection\Collection
global: GlobalManager
flatDb: FileStorage
FlatRepository: FileStorageRepository
controllerSettings: App\Core\Settings\Model\ControllerSettingModel
settings: App\Core\Settings\Settings
