formBuilder: FormBuilder
eventDispatcher: EventDispatcher
error: CoreError
tableGrid: Datatable
collection: Collection
global: GlobalManager
flatDb: FileStorage
FlatRepository: FileStorageRepository
controllerSettings: ControllerSettingModel
settings: Settings
