get: # Http Get ===========================================
  "/":
    controller: home
    method: index
    namespace: Client
  "home":
    controller: home
    method: index
    namespace: Client
  "learn":
    controller: learning
    method: index
    namespace: Client
  login:
    controller: security
    method: login
    namespace: Client
  assets:
    controller: assets
    method: get_asset
    namespace: Client
  admin/{controller}/{method}:
    namespace: Admin
  admin/{controller}/{method}/{id:[\da-f]+}:
    namespace: Admin
  client/{controller}/{method}:
    namespace: Client
  client/{controller}/{method}/{id:[\da-f]+}:
    namespace: Client
  test: errors
post: # Http Post method =========================================================
  visitors:
    controller: visitors
    method: track
    namespace: Client
  ajaxLogin:
    controller: auth
    method: ajaxlogin
    namespace: Client
  client/{controller}/{method}:
    namespace: Client
  client/{controller}/{method}/{id:[\da-f]+}:
    namespace: Client
